// Client-side search across every Redis command, for the commands overview page.
//
// NOTE (Mintlify constraint, validated): an exported component CANNOT reference a
// sibling module-level `export const`. Mintlify compiles each export in isolation,
// so the data array MUST live inside the component's own function body.
// React hooks (useState, etc.) are pre-injected by Mintlify - no import needed.

export const CommandSearch = () => {
  const MAX_RESULTS = 30;

  const commands = [
    { title: "BITCOUNT", category: "Bitmap", description: "Count set bits in a string.", href: "/redis/commands/bitmap/bitcount" },
    { title: "BITFIELD_RO", category: "Bitmap", description: "Read bitfield values.", href: "/redis/commands/bitmap/bitfield-ro" },
    { title: "BITFIELD", category: "Bitmap", description: "Perform arbitrary bitfield operations.", href: "/redis/commands/bitmap/bitfield" },
    { title: "BITOP", category: "Bitmap", description: "Perform bitwise operations between strings.", href: "/redis/commands/bitmap/bitop" },
    { title: "BITPOS", category: "Bitmap", description: "Find first bit set or clear in a string.", href: "/redis/commands/bitmap/bitpos" },
    { title: "GETBIT", category: "Bitmap", description: "Get the bit value at offset.", href: "/redis/commands/bitmap/getbit" },
    { title: "SETBIT", category: "Bitmap", description: "Set or clear the bit at offset.", href: "/redis/commands/bitmap/setbit" },
    { title: "AUTH", category: "Connection", description: "Authenticate to the server.", href: "/redis/commands/connection/auth" },
    { title: "CLIENT GETNAME", category: "Connection", description: "Get the current connection name.", href: "/redis/commands/connection/client-getname" },
    { title: "CLIENT ID", category: "Connection", description: "Get the current client ID.", href: "/redis/commands/connection/client-id" },
    { title: "CLIENT INFO", category: "Connection", description: "Get info about current connection.", href: "/redis/commands/connection/client-info" },
    { title: "CLIENT LIST", category: "Connection", description: "List all client connections.", href: "/redis/commands/connection/client-list" },
    { title: "CLIENT SETINFO", category: "Connection", description: "Set client connection attributes.", href: "/redis/commands/connection/client-setinfo" },
    { title: "CLIENT SETNAME", category: "Connection", description: "Set the connection name.", href: "/redis/commands/connection/client-setname" },
    { title: "ECHO", category: "Connection", description: "Echo the given string.", href: "/redis/commands/connection/echo" },
    { title: "HELLO", category: "Connection", description: "Handshake with Redis protocol.", href: "/redis/commands/connection/hello" },
    { title: "PING", category: "Connection", description: "Ping the server.", href: "/redis/commands/connection/ping" },
    { title: "QUIT", category: "Connection", description: "Close the connection.", href: "/redis/commands/connection/quit" },
    { title: "RESET", category: "Connection", description: "Reset the connection.", href: "/redis/commands/connection/reset" },
    { title: "SELECT", category: "Connection", description: "Select the database by index.", href: "/redis/commands/connection/select" },
    { title: "FCALL_RO", category: "Functions", description: "Call a read-only function.", href: "/redis/commands/functions/fcall-ro" },
    { title: "FCALL", category: "Functions", description: "Call a function.", href: "/redis/commands/functions/fcall" },
    { title: "FUNCTION DELETE", category: "Functions", description: "Delete a library.", href: "/redis/commands/functions/function-delete" },
    { title: "FUNCTION FLUSH", category: "Functions", description: "Delete all libraries.", href: "/redis/commands/functions/function-flush" },
    { title: "FUNCTION KILL", category: "Functions", description: "Kill a running function.", href: "/redis/commands/functions/function-kill" },
    { title: "FUNCTION LIST", category: "Functions", description: "List all libraries.", href: "/redis/commands/functions/function-list" },
    { title: "FUNCTION LOAD", category: "Functions", description: "Load a library.", href: "/redis/commands/functions/function-load" },
    { title: "FUNCTION STATS", category: "Functions", description: "Get function execution stats.", href: "/redis/commands/functions/function-stats" },
    { title: "COPY", category: "Generic", description: "Copy a key to another key.", href: "/redis/commands/generic/copy" },
    { title: "DEL", category: "Generic", description: "Delete one or more keys.", href: "/redis/commands/generic/del" },
    { title: "DUMP", category: "Generic", description: "Serialize a key's value.", href: "/redis/commands/generic/dump" },
    { title: "EXISTS", category: "Generic", description: "Check if keys exist.", href: "/redis/commands/generic/exists" },
    { title: "EXPIRE", category: "Generic", description: "Set a key's TTL in seconds.", href: "/redis/commands/generic/expire" },
    { title: "EXPIREAT", category: "Generic", description: "Set expiry as Unix timestamp.", href: "/redis/commands/generic/expireat" },
    { title: "EXPIRETIME", category: "Generic", description: "Get expiry as Unix timestamp.", href: "/redis/commands/generic/expiretime" },
    { title: "KEYS", category: "Generic", description: "Find keys matching a pattern.", href: "/redis/commands/generic/keys" },
    { title: "MEMORY USAGE", category: "Generic", description: "Estimate memory used by a key.", href: "/redis/commands/generic/memory-usage" },
    { title: "PERSIST", category: "Generic", description: "Remove the expiration from a key.", href: "/redis/commands/generic/persist" },
    { title: "PEXPIRE", category: "Generic", description: "Set a key's TTL in milliseconds.", href: "/redis/commands/generic/pexpire" },
    { title: "PEXPIREAT", category: "Generic", description: "Set expiry as Unix ms timestamp.", href: "/redis/commands/generic/pexpireat" },
    { title: "PEXPIRETIME", category: "Generic", description: "Get expiry as Unix ms timestamp.", href: "/redis/commands/generic/pexpiretime" },
    { title: "PTTL", category: "Generic", description: "Get TTL in milliseconds.", href: "/redis/commands/generic/pttl" },
    { title: "RANDOMKEY", category: "Generic", description: "Return a random key.", href: "/redis/commands/generic/randomkey" },
    { title: "RENAME", category: "Generic", description: "Rename a key.", href: "/redis/commands/generic/rename" },
    { title: "RENAMENX", category: "Generic", description: "Rename a key if new key doesn't exist.", href: "/redis/commands/generic/renamenx" },
    { title: "RESTORE", category: "Generic", description: "Deserialize and restore a key.", href: "/redis/commands/generic/restore" },
    { title: "SCAN", category: "Generic", description: "Incrementally iterate keys.", href: "/redis/commands/generic/scan" },
    { title: "TOUCH", category: "Generic", description: "Update last access time of keys.", href: "/redis/commands/generic/touch" },
    { title: "TTL", category: "Generic", description: "Get TTL in seconds.", href: "/redis/commands/generic/ttl" },
    { title: "TYPE", category: "Generic", description: "Get the type of a key.", href: "/redis/commands/generic/type" },
    { title: "UNLINK", category: "Generic", description: "Delete keys asynchronously.", href: "/redis/commands/generic/unlink" },
    { title: "WAIT", category: "Generic", description: "Wait for replica acknowledgements.", href: "/redis/commands/generic/wait" },
    { title: "WAITAOF", category: "Generic", description: "Wait for local and replica persistence.", href: "/redis/commands/generic/waitaof" },
    { title: "GEOADD", category: "Geo", description: "Add geospatial items.", href: "/redis/commands/geo/geoadd" },
    { title: "GEODIST", category: "Geo", description: "Get distance between two members.", href: "/redis/commands/geo/geodist" },
    { title: "GEOHASH", category: "Geo", description: "Get geohash strings for members.", href: "/redis/commands/geo/geohash" },
    { title: "GEOPOS", category: "Geo", description: "Get coordinates of members.", href: "/redis/commands/geo/geopos" },
    { title: "GEORADIUS_RO", category: "Geo", description: "Find members within a radius of a point.", href: "/redis/commands/geo/georadius-ro" },
    { title: "GEORADIUS", category: "Geo", description: "Find members within a radius of a point.", href: "/redis/commands/geo/georadius" },
    { title: "GEORADIUSBYMEMBER_RO", category: "Geo", description: "Find members within a radius of another member.", href: "/redis/commands/geo/georadiusbymember-ro" },
    { title: "GEORADIUSBYMEMBER", category: "Geo", description: "Find members within a radius of another member.", href: "/redis/commands/geo/georadiusbymember" },
    { title: "GEOSEARCH", category: "Geo", description: "Search for members in an area.", href: "/redis/commands/geo/geosearch" },
    { title: "GEOSEARCHSTORE", category: "Geo", description: "Store geosearch results.", href: "/redis/commands/geo/geosearchstore" },
    { title: "HDEL", category: "Hash", description: "Delete one or more hash fields.", href: "/redis/commands/hash/hdel" },
    { title: "HEXISTS", category: "Hash", description: "Check if a hash field exists.", href: "/redis/commands/hash/hexists" },
    { title: "HEXPIRE", category: "Hash", description: "Set field TTL in seconds.", href: "/redis/commands/hash/hexpire" },
    { title: "HEXPIREAT", category: "Hash", description: "Set field expiry as timestamp.", href: "/redis/commands/hash/hexpireat" },
    { title: "HEXPIRETIME", category: "Hash", description: "Get field expiry as timestamp.", href: "/redis/commands/hash/hexpiretime" },
    { title: "HGET", category: "Hash", description: "Get the value of a hash field.", href: "/redis/commands/hash/hget" },
    { title: "HGETALL", category: "Hash", description: "Get all fields and values.", href: "/redis/commands/hash/hgetall" },
    { title: "HGETDEL", category: "Hash", description: "Get and delete hash fields.", href: "/redis/commands/hash/hgetdel" },
    { title: "HGETEX", category: "Hash", description: "Get fields and set their expiry.", href: "/redis/commands/hash/hgetex" },
    { title: "HINCRBY", category: "Hash", description: "Increment integer value of a field.", href: "/redis/commands/hash/hincrby" },
    { title: "HINCRBYFLOAT", category: "Hash", description: "Increment float value of a field.", href: "/redis/commands/hash/hincrbyfloat" },
    { title: "HKEYS", category: "Hash", description: "Get all fields in a hash.", href: "/redis/commands/hash/hkeys" },
    { title: "HLEN", category: "Hash", description: "Get number of fields in a hash.", href: "/redis/commands/hash/hlen" },
    { title: "HMGET", category: "Hash", description: "Get values of multiple fields.", href: "/redis/commands/hash/hmget" },
    { title: "HMSET", category: "Hash", description: "Set multiple hash fields.", href: "/redis/commands/hash/hmset" },
    { title: "HPERSIST", category: "Hash", description: "Remove field expiration.", href: "/redis/commands/hash/hpersist" },
    { title: "HPEXPIRE", category: "Hash", description: "Set field TTL in milliseconds.", href: "/redis/commands/hash/hpexpire" },
    { title: "HPEXPIREAT", category: "Hash", description: "Set field expiry as ms timestamp.", href: "/redis/commands/hash/hpexpireat" },
    { title: "HPEXPIRETIME", category: "Hash", description: "Get field expiry as ms timestamp.", href: "/redis/commands/hash/hpexpiretime" },
    { title: "HPTTL", category: "Hash", description: "Get field TTL in milliseconds.", href: "/redis/commands/hash/hpttl" },
    { title: "HRANDFIELD", category: "Hash", description: "Get random fields from a hash.", href: "/redis/commands/hash/hrandfield" },
    { title: "HSCAN", category: "Hash", description: "Incrementally iterate hash fields.", href: "/redis/commands/hash/hscan" },
    { title: "HSET", category: "Hash", description: "Set hash field values.", href: "/redis/commands/hash/hset" },
    { title: "HSETEX", category: "Hash", description: "Set fields with expiration.", href: "/redis/commands/hash/hsetex" },
    { title: "HSETNX", category: "Hash", description: "Set field only if it doesn't exist.", href: "/redis/commands/hash/hsetnx" },
    { title: "HSTRLEN", category: "Hash", description: "Get length of a field's value.", href: "/redis/commands/hash/hstrlen" },
    { title: "HTTL", category: "Hash", description: "Get field TTL in seconds.", href: "/redis/commands/hash/httl" },
    { title: "HVALS", category: "Hash", description: "Get all values in a hash.", href: "/redis/commands/hash/hvals" },
    { title: "PFADD", category: "HyperLogLog", description: "Add elements to HyperLogLog.", href: "/redis/commands/hyperloglog/pfadd" },
    { title: "PFCOUNT", category: "HyperLogLog", description: "Get estimated cardinality.", href: "/redis/commands/hyperloglog/pfcount" },
    { title: "PFMERGE", category: "HyperLogLog", description: "Merge multiple HyperLogLogs.", href: "/redis/commands/hyperloglog/pfmerge" },
    { title: "JSON.ARRAPPEND", category: "JSON", description: "Append values to JSON array.", href: "/redis/commands/json/json-arrappend" },
    { title: "JSON.ARRINDEX", category: "JSON", description: "Find index of value in array.", href: "/redis/commands/json/json-arrindex" },
    { title: "JSON.ARRINSERT", category: "JSON", description: "Insert values into JSON array.", href: "/redis/commands/json/json-arrinsert" },
    { title: "JSON.ARRLEN", category: "JSON", description: "Get JSON array length.", href: "/redis/commands/json/json-arrlen" },
    { title: "JSON.ARRPOP", category: "JSON", description: "Pop value from JSON array.", href: "/redis/commands/json/json-arrpop" },
    { title: "JSON.ARRTRIM", category: "JSON", description: "Trim JSON array to range.", href: "/redis/commands/json/json-arrtrim" },
    { title: "JSON.CLEAR", category: "JSON", description: "Clear JSON values.", href: "/redis/commands/json/json-clear" },
    { title: "JSON.DEBUG", category: "JSON", description: "Inspect JSON memory usage.", href: "/redis/commands/json/json-debug" },
    { title: "JSON.DEL", category: "JSON", description: "Delete JSON values.", href: "/redis/commands/json/json-del" },
    { title: "JSON.FORGET", category: "JSON", description: "Delete JSON values (alias of JSON.DEL).", href: "/redis/commands/json/json-forget" },
    { title: "JSON.GET", category: "JSON", description: "Get JSON values.", href: "/redis/commands/json/json-get" },
    { title: "JSON.MERGE", category: "JSON", description: "Merge JSON values.", href: "/redis/commands/json/json-merge" },
    { title: "JSON.MGET", category: "JSON", description: "Get values from multiple keys.", href: "/redis/commands/json/json-mget" },
    { title: "JSON.MSET", category: "JSON", description: "Set values in multiple keys.", href: "/redis/commands/json/json-mset" },
    { title: "JSON.NUMINCRBY", category: "JSON", description: "Increment JSON number.", href: "/redis/commands/json/json-numincrby" },
    { title: "JSON.NUMMULTBY", category: "JSON", description: "Multiply JSON number.", href: "/redis/commands/json/json-nummultby" },
    { title: "JSON.OBJKEYS", category: "JSON", description: "Get JSON object keys.", href: "/redis/commands/json/json-objkeys" },
    { title: "JSON.OBJLEN", category: "JSON", description: "Get JSON object size.", href: "/redis/commands/json/json-objlen" },
    { title: "JSON.RESP", category: "JSON", description: "Get JSON in RESP format.", href: "/redis/commands/json/json-resp" },
    { title: "JSON.SET", category: "JSON", description: "Set JSON value.", href: "/redis/commands/json/json-set" },
    { title: "JSON.STRAPPEND", category: "JSON", description: "Append to JSON string.", href: "/redis/commands/json/json-strappend" },
    { title: "JSON.STRLEN", category: "JSON", description: "Get JSON string length.", href: "/redis/commands/json/json-strlen" },
    { title: "JSON.TOGGLE", category: "JSON", description: "Toggle JSON boolean.", href: "/redis/commands/json/json-toggle" },
    { title: "JSON.TYPE", category: "JSON", description: "Get JSON value type.", href: "/redis/commands/json/json-type" },
    { title: "BLMOVE", category: "List", description: "Move an element between lists, blocking until one arrives.", href: "/redis/commands/list/blmove" },
    { title: "BLMPOP", category: "List", description: "Pop from the first non-empty list, blocking until one arrives.", href: "/redis/commands/list/blmpop" },
    { title: "BLPOP", category: "List", description: "Pop from the head of a list, blocking until an element arrives.", href: "/redis/commands/list/blpop" },
    { title: "BRPOP", category: "List", description: "Pop from the tail of a list, blocking until an element arrives.", href: "/redis/commands/list/brpop" },
    { title: "BRPOPLPUSH", category: "List", description: "Pop from a list's tail and push it to another, blocking until an element arrives.", href: "/redis/commands/list/brpoplpush" },
    { title: "LINDEX", category: "List", description: "Get element by index.", href: "/redis/commands/list/lindex" },
    { title: "LINSERT", category: "List", description: "Insert before or after pivot.", href: "/redis/commands/list/linsert" },
    { title: "LLEN", category: "List", description: "Get list length.", href: "/redis/commands/list/llen" },
    { title: "LMOVE", category: "List", description: "Move element between lists.", href: "/redis/commands/list/lmove" },
    { title: "LMPOP", category: "List", description: "Pop from the first non-empty list.", href: "/redis/commands/list/lmpop" },
    { title: "LPOP", category: "List", description: "Pop from list head.", href: "/redis/commands/list/lpop" },
    { title: "LPOS", category: "List", description: "Find the position of an element.", href: "/redis/commands/list/lpos" },
    { title: "LPUSH", category: "List", description: "Push to list head.", href: "/redis/commands/list/lpush" },
    { title: "LPUSHX", category: "List", description: "Push to head if list exists.", href: "/redis/commands/list/lpushx" },
    { title: "LRANGE", category: "List", description: "Get range of elements.", href: "/redis/commands/list/lrange" },
    { title: "LREM", category: "List", description: "Remove elements by value.", href: "/redis/commands/list/lrem" },
    { title: "LSET", category: "List", description: "Set element at index.", href: "/redis/commands/list/lset" },
    { title: "LTRIM", category: "List", description: "Trim list to range.", href: "/redis/commands/list/ltrim" },
    { title: "RPOP", category: "List", description: "Pop from list tail.", href: "/redis/commands/list/rpop" },
    { title: "RPOPLPUSH", category: "List", description: "Pop from tail and push to head.", href: "/redis/commands/list/rpoplpush" },
    { title: "RPUSH", category: "List", description: "Push to list tail.", href: "/redis/commands/list/rpush" },
    { title: "RPUSHX", category: "List", description: "Push to tail if list exists.", href: "/redis/commands/list/rpushx" },
    { title: "PSUBSCRIBE", category: "Pub/Sub", description: "Subscribe to pattern channels.", href: "/redis/commands/pub-sub/psubscribe" },
    { title: "PUBLISH", category: "Pub/Sub", description: "Publish message to channel.", href: "/redis/commands/pub-sub/publish" },
    { title: "PUBSUB", category: "Pub/Sub", description: "Inspect pub/sub state.", href: "/redis/commands/pub-sub/pubsub" },
    { title: "PUNSUBSCRIBE", category: "Pub/Sub", description: "Unsubscribe from patterns.", href: "/redis/commands/pub-sub/punsubscribe" },
    { title: "SUBSCRIBE", category: "Pub/Sub", description: "Subscribe to channels.", href: "/redis/commands/pub-sub/subscribe" },
    { title: "UNSUBSCRIBE", category: "Pub/Sub", description: "Unsubscribe from channels.", href: "/redis/commands/pub-sub/unsubscribe" },
    { title: "EVAL_RO", category: "Scripting", description: "Execute read-only Lua script.", href: "/redis/commands/scripting/eval-ro" },
    { title: "EVAL", category: "Scripting", description: "Execute a Lua script.", href: "/redis/commands/scripting/eval" },
    { title: "EVALSHA_RO", category: "Scripting", description: "Run a cached script that does not write.", href: "/redis/commands/scripting/evalsha-ro" },
    { title: "EVALSHA", category: "Scripting", description: "Execute cached Lua script by SHA.", href: "/redis/commands/scripting/evalsha" },
    { title: "SCRIPT EXISTS", category: "Scripting", description: "Check if scripts exist in cache.", href: "/redis/commands/scripting/script-exists" },
    { title: "SCRIPT FLUSH", category: "Scripting", description: "Clear the script cache.", href: "/redis/commands/scripting/script-flush" },
    { title: "SCRIPT KILL", category: "Scripting", description: "Stop a running read-only script.", href: "/redis/commands/scripting/script-kill" },
    { title: "SCRIPT LOAD", category: "Scripting", description: "Load script into cache.", href: "/redis/commands/scripting/script-load" },
    { title: "SEARCH.AGGREGATE", category: "Search", description: "Compute analytics over matching documents.", href: "/redis/commands/search/search-aggregate" },
    { title: "SEARCH.ALIASADD", category: "Search", description: "Create or update a search index alias.", href: "/redis/commands/search/search-aliasadd" },
    { title: "SEARCH.ALIASDEL", category: "Search", description: "Delete a search index alias.", href: "/redis/commands/search/search-aliasdel" },
    { title: "SEARCH.COUNT", category: "Search", description: "Count documents matching a query.", href: "/redis/commands/search/search-count" },
    { title: "SEARCH.CREATE", category: "Search", description: "Create a search index.", href: "/redis/commands/search/search-create" },
    { title: "SEARCH.DESCRIBE", category: "Search", description: "Return metadata about a search index.", href: "/redis/commands/search/search-describe" },
    { title: "SEARCH.DROP", category: "Search", description: "Drop a search index without deleting its keys.", href: "/redis/commands/search/search-drop" },
    { title: "SEARCH.LISTALIASES", category: "Search", description: "List search index aliases.", href: "/redis/commands/search/search-listaliases" },
    { title: "SEARCH.LISTINDEXES", category: "Search", description: "List search indexes in the database.", href: "/redis/commands/search/search-listindexes" },
    { title: "SEARCH.QUERY", category: "Search", description: "Search documents with a JSON filter.", href: "/redis/commands/search/search-query" },
    { title: "SEARCH.REINDEX", category: "Search", description: "Rebuild a search index from the current matching data.", href: "/redis/commands/search/search-reindex" },
    { title: "SEARCH.WAITINDEXING", category: "Search", description: "Wait until pending index updates are visible.", href: "/redis/commands/search/search-waitindexing" },
    { title: "ACL", category: "Server", description: "Manage access control list.", href: "/redis/commands/server/acl" },
    { title: "COMMAND", category: "Server", description: "Get command metadata.", href: "/redis/commands/server/command" },
    { title: "CONFIG GET", category: "Server", description: "Read runtime configuration.", href: "/redis/commands/server/config-get" },
    { title: "CONFIG SET", category: "Server", description: "Change runtime configuration.", href: "/redis/commands/server/config-set" },
    { title: "DBSIZE", category: "Server", description: "Get number of keys in database.", href: "/redis/commands/server/dbsize" },
    { title: "FLUSHALL", category: "Server", description: "Delete all keys in all databases.", href: "/redis/commands/server/flushall" },
    { title: "FLUSHDB", category: "Server", description: "Delete all keys in current database.", href: "/redis/commands/server/flushdb" },
    { title: "INFO", category: "Server", description: "Get server statistics and information.", href: "/redis/commands/server/info" },
    { title: "MONITOR", category: "Server", description: "Stream all commands received.", href: "/redis/commands/server/monitor" },
    { title: "TIME", category: "Server", description: "Get current server time.", href: "/redis/commands/server/time" },
    { title: "SADD", category: "Set", description: "Add members to a set.", href: "/redis/commands/set/sadd" },
    { title: "SCARD", category: "Set", description: "Get set cardinality.", href: "/redis/commands/set/scard" },
    { title: "SDIFF", category: "Set", description: "Get set difference.", href: "/redis/commands/set/sdiff" },
    { title: "SDIFFSTORE", category: "Set", description: "Store set difference.", href: "/redis/commands/set/sdiffstore" },
    { title: "SINTER", category: "Set", description: "Get set intersection.", href: "/redis/commands/set/sinter" },
    { title: "SINTERCARD", category: "Set", description: "Get intersection cardinality.", href: "/redis/commands/set/sintercard" },
    { title: "SINTERSTORE", category: "Set", description: "Store set intersection.", href: "/redis/commands/set/sinterstore" },
    { title: "SISMEMBER", category: "Set", description: "Check if member exists in set.", href: "/redis/commands/set/sismember" },
    { title: "SMEMBERS", category: "Set", description: "Get all set members.", href: "/redis/commands/set/smembers" },
    { title: "SMISMEMBER", category: "Set", description: "Check membership of several values.", href: "/redis/commands/set/smismember" },
    { title: "SMOVE", category: "Set", description: "Move member between sets.", href: "/redis/commands/set/smove" },
    { title: "SPOP", category: "Set", description: "Remove and return random members.", href: "/redis/commands/set/spop" },
    { title: "SRANDMEMBER", category: "Set", description: "Get random members.", href: "/redis/commands/set/srandmember" },
    { title: "SREM", category: "Set", description: "Remove members from a set.", href: "/redis/commands/set/srem" },
    { title: "SSCAN", category: "Set", description: "Incrementally iterate set members.", href: "/redis/commands/set/sscan" },
    { title: "SUNION", category: "Set", description: "Get set union.", href: "/redis/commands/set/sunion" },
    { title: "SUNIONSTORE", category: "Set", description: "Store set union.", href: "/redis/commands/set/sunionstore" },
    { title: "BZMPOP", category: "Sorted Set", description: "Pop from the first non-empty sorted set, blocking until one arrives.", href: "/redis/commands/sorted-set/bzmpop" },
    { title: "BZPOPMAX", category: "Sorted Set", description: "Pop the highest-scoring member, blocking until one arrives.", href: "/redis/commands/sorted-set/bzpopmax" },
    { title: "BZPOPMIN", category: "Sorted Set", description: "Pop the lowest-scoring member, blocking until one arrives.", href: "/redis/commands/sorted-set/bzpopmin" },
    { title: "ZADD", category: "Sorted Set", description: "Add members with scores.", href: "/redis/commands/sorted-set/zadd" },
    { title: "ZCARD", category: "Sorted Set", description: "Get sorted set cardinality.", href: "/redis/commands/sorted-set/zcard" },
    { title: "ZCOUNT", category: "Sorted Set", description: "Count members in score range.", href: "/redis/commands/sorted-set/zcount" },
    { title: "ZDIFF", category: "Sorted Set", description: "Get sorted set difference.", href: "/redis/commands/sorted-set/zdiff" },
    { title: "ZDIFFSTORE", category: "Sorted Set", description: "Store sorted set difference.", href: "/redis/commands/sorted-set/zdiffstore" },
    { title: "ZINCRBY", category: "Sorted Set", description: "Increment member's score.", href: "/redis/commands/sorted-set/zincrby" },
    { title: "ZINTER", category: "Sorted Set", description: "Get sorted set intersection.", href: "/redis/commands/sorted-set/zinter" },
    { title: "ZINTERCARD", category: "Sorted Set", description: "Get intersection cardinality.", href: "/redis/commands/sorted-set/zintercard" },
    { title: "ZINTERSTORE", category: "Sorted Set", description: "Store sorted set intersection.", href: "/redis/commands/sorted-set/zinterstore" },
    { title: "ZLEXCOUNT", category: "Sorted Set", description: "Count members in lex range.", href: "/redis/commands/sorted-set/zlexcount" },
    { title: "ZMPOP", category: "Sorted Set", description: "Pop from the first non-empty sorted set.", href: "/redis/commands/sorted-set/zmpop" },
    { title: "ZMSCORE", category: "Sorted Set", description: "Get scores of multiple members.", href: "/redis/commands/sorted-set/zmscore" },
    { title: "ZPOPMAX", category: "Sorted Set", description: "Pop members with highest scores.", href: "/redis/commands/sorted-set/zpopmax" },
    { title: "ZPOPMIN", category: "Sorted Set", description: "Pop members with lowest scores.", href: "/redis/commands/sorted-set/zpopmin" },
    { title: "ZRANDMEMBER", category: "Sorted Set", description: "Get random members.", href: "/redis/commands/sorted-set/zrandmember" },
    { title: "ZRANGE", category: "Sorted Set", description: "Get members by index, score, or lex range.", href: "/redis/commands/sorted-set/zrange" },
    { title: "ZRANGEBYLEX", category: "Sorted Set", description: "Get members by lex range.", href: "/redis/commands/sorted-set/zrangebylex" },
    { title: "ZRANGEBYSCORE", category: "Sorted Set", description: "Get members by score range.", href: "/redis/commands/sorted-set/zrangebyscore" },
    { title: "ZRANGESTORE", category: "Sorted Set", description: "Store the result of a range query.", href: "/redis/commands/sorted-set/zrangestore" },
    { title: "ZRANK", category: "Sorted Set", description: "Get member's rank.", href: "/redis/commands/sorted-set/zrank" },
    { title: "ZREM", category: "Sorted Set", description: "Remove members.", href: "/redis/commands/sorted-set/zrem" },
    { title: "ZREMRANGEBYLEX", category: "Sorted Set", description: "Remove members by lex range.", href: "/redis/commands/sorted-set/zremrangebylex" },
    { title: "ZREMRANGEBYRANK", category: "Sorted Set", description: "Remove members by rank range.", href: "/redis/commands/sorted-set/zremrangebyrank" },
    { title: "ZREMRANGEBYSCORE", category: "Sorted Set", description: "Remove members by score range.", href: "/redis/commands/sorted-set/zremrangebyscore" },
    { title: "ZREVRANGE", category: "Sorted Set", description: "Get members in reverse order.", href: "/redis/commands/sorted-set/zrevrange" },
    { title: "ZREVRANGEBYLEX", category: "Sorted Set", description: "List members in a lexicographic range, in reverse order.", href: "/redis/commands/sorted-set/zrevrangebylex" },
    { title: "ZREVRANGEBYSCORE", category: "Sorted Set", description: "List members in a score range, highest score first.", href: "/redis/commands/sorted-set/zrevrangebyscore" },
    { title: "ZREVRANK", category: "Sorted Set", description: "Get member's reverse rank.", href: "/redis/commands/sorted-set/zrevrank" },
    { title: "ZSCAN", category: "Sorted Set", description: "Incrementally iterate sorted set.", href: "/redis/commands/sorted-set/zscan" },
    { title: "ZSCORE", category: "Sorted Set", description: "Get member's score.", href: "/redis/commands/sorted-set/zscore" },
    { title: "ZUNION", category: "Sorted Set", description: "Get sorted set union.", href: "/redis/commands/sorted-set/zunion" },
    { title: "ZUNIONSTORE", category: "Sorted Set", description: "Store sorted set union.", href: "/redis/commands/sorted-set/zunionstore" },
    { title: "XACK", category: "Streams", description: "Acknowledge stream messages.", href: "/redis/commands/streams/xack" },
    { title: "XACKDEL", category: "Streams", description: "Acknowledge and delete messages.", href: "/redis/commands/streams/xackdel" },
    { title: "XADD", category: "Streams", description: "Add entry to stream.", href: "/redis/commands/streams/xadd" },
    { title: "XAUTOCLAIM", category: "Streams", description: "Auto-claim idle messages.", href: "/redis/commands/streams/xautoclaim" },
    { title: "XCLAIM", category: "Streams", description: "Claim pending messages.", href: "/redis/commands/streams/xclaim" },
    { title: "XDEL", category: "Streams", description: "Delete stream entries.", href: "/redis/commands/streams/xdel" },
    { title: "XDELEX", category: "Streams", description: "Delete entries with reference control.", href: "/redis/commands/streams/xdelex" },
    { title: "XGROUP", category: "Streams", description: "Manage consumer groups.", href: "/redis/commands/streams/xgroup" },
    { title: "XINFO CONSUMERS", category: "Streams", description: "List group consumers.", href: "/redis/commands/streams/xinfo-consumers" },
    { title: "XINFO GROUPS", category: "Streams", description: "List stream groups.", href: "/redis/commands/streams/xinfo-groups" },
    { title: "XINFO STREAM", category: "Streams", description: "Get stream info.", href: "/redis/commands/streams/xinfo-stream" },
    { title: "XLEN", category: "Streams", description: "Get stream length.", href: "/redis/commands/streams/xlen" },
    { title: "XPENDING", category: "Streams", description: "Get pending messages info.", href: "/redis/commands/streams/xpending" },
    { title: "XRANGE", category: "Streams", description: "Get range of stream entries.", href: "/redis/commands/streams/xrange" },
    { title: "XREAD", category: "Streams", description: "Read stream entries.", href: "/redis/commands/streams/xread" },
    { title: "XREADGROUP", category: "Streams", description: "Read as consumer group.", href: "/redis/commands/streams/xreadgroup" },
    { title: "XREVRANGE", category: "Streams", description: "Get range in reverse order.", href: "/redis/commands/streams/xrevrange" },
    { title: "XTRIM", category: "Streams", description: "Trim stream to max length.", href: "/redis/commands/streams/xtrim" },
    { title: "APPEND", category: "String", description: "Append value to a string.", href: "/redis/commands/string/append" },
    { title: "DECR", category: "String", description: "Decrement integer value by 1.", href: "/redis/commands/string/decr" },
    { title: "DECRBY", category: "String", description: "Decrement integer by amount.", href: "/redis/commands/string/decrby" },
    { title: "DELEX", category: "String", description: "Delete a string when a condition matches.", href: "/redis/commands/string/delex" },
    { title: "DIGEST", category: "String", description: "Get the digest of a string value.", href: "/redis/commands/string/digest" },
    { title: "GET", category: "String", description: "Get string value.", href: "/redis/commands/string/get" },
    { title: "GETDEL", category: "String", description: "Get value and delete key.", href: "/redis/commands/string/getdel" },
    { title: "GETEX", category: "String", description: "Get value and set expiration.", href: "/redis/commands/string/getex" },
    { title: "GETRANGE", category: "String", description: "Get substring of string.", href: "/redis/commands/string/getrange" },
    { title: "GETSET", category: "String", description: "Set value and return old value.", href: "/redis/commands/string/getset" },
    { title: "INCR", category: "String", description: "Increment integer value by 1.", href: "/redis/commands/string/incr" },
    { title: "INCRBY", category: "String", description: "Increment integer by amount.", href: "/redis/commands/string/incrby" },
    { title: "INCRBYFLOAT", category: "String", description: "Increment float by amount.", href: "/redis/commands/string/incrbyfloat" },
    { title: "MGET", category: "String", description: "Get values of multiple keys.", href: "/redis/commands/string/mget" },
    { title: "MSET", category: "String", description: "Set multiple keys at once.", href: "/redis/commands/string/mset" },
    { title: "MSETNX", category: "String", description: "Set multiple keys if none exist.", href: "/redis/commands/string/msetnx" },
    { title: "PSETEX", category: "String", description: "Set value with ms expiration.", href: "/redis/commands/string/psetex" },
    { title: "SET", category: "String", description: "Set string value.", href: "/redis/commands/string/set" },
    { title: "SETEX", category: "String", description: "Set value with expiration.", href: "/redis/commands/string/setex" },
    { title: "SETNX", category: "String", description: "Set value if key doesn't exist.", href: "/redis/commands/string/setnx" },
    { title: "SETRANGE", category: "String", description: "Overwrite part of string.", href: "/redis/commands/string/setrange" },
    { title: "STRLEN", category: "String", description: "Get string length.", href: "/redis/commands/string/strlen" },
    { title: "DISCARD", category: "Transactions", description: "Discard queued commands.", href: "/redis/commands/transactions/discard" },
    { title: "EXEC", category: "Transactions", description: "Execute queued commands.", href: "/redis/commands/transactions/exec" },
    { title: "MULTI", category: "Transactions", description: "Start a transaction.", href: "/redis/commands/transactions/multi" },
    { title: "UNWATCH", category: "Transactions", description: "Unwatch all keys.", href: "/redis/commands/transactions/unwatch" },
    { title: "WATCH", category: "Transactions", description: "Watch keys for changes.", href: "/redis/commands/transactions/watch" },
  ];

  const [query, setQuery] = useState("");
  const q = query.trim().toLowerCase();

  const results = q
    ? commands.filter(
        (c) =>
          c.title.toLowerCase().includes(q) ||
          c.description.toLowerCase().includes(q) ||
          c.category.toLowerCase().includes(q),
      )
    : [];

  return (
    <div className="u-cmd-search">
      <input
        type="text"
        className="u-cmd-search__input"
        placeholder="Search commands across all categories, e.g. GEOADD, expire, sorted set…"
        value={query}
        onChange={(e) => setQuery(e.target.value)}
        aria-label="Search Redis commands"
      />
      {q ? (
        results.length ? (
          <>
            <div className="u-grid u-grid--2 u-cmd-search__results">
              {results.slice(0, MAX_RESULTS).map((c) => (
                <a key={c.href} href={c.href} className="u-card">
                  <div className="u-card__body">
                    <div className="u-card__title">
                      {c.title}
                      <span className="u-cmd-tag">{c.category}</span>
                    </div>
                    <div className="u-card__desc">{c.description}</div>
                  </div>
                </a>
              ))}
            </div>
            {results.length > MAX_RESULTS ? (
              <p className="u-cmd-search__meta">
                Showing {MAX_RESULTS} of {results.length} matches. Refine your search to narrow the results.
              </p>
            ) : null}
          </>
        ) : (
          <p className="u-cmd-search__empty">No commands match &ldquo;{query}&rdquo;.</p>
        )
      ) : null}
      <hr className="u-cmd-search__divider" />
    </div>
  );
};
